<a href="https://colab.research.google.com/github/brendharosa/primeiro1/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Colab colaborativo para manipulação de dados usando a biblioteca Pandas**

Para que todas as soluções propostas funcionem vamos seguir algumas regras:
* Mantenha as primeira duas células inalteradas;
* Crie cópias do dataset principal para as soluções;
* Use comentários para explicar a solução proposta;
* Insira seu nome na solução;
* A terceira célula é exemplo de como inserir.

# Importando o pandas (não altere)

In [3]:
import pandas as pd

# Criando um dataset importando um arquivo csv (não altere).

O arquivo *clima_historico_municipal.csv* contém um registro por município, identificado por código IBGE, nome e UF. Para cada município, a base informa o período de referência, a fonte climática, o método de processamento e um conjunto de variáveis mensais agregadas historicamente. As variáveis climáticas presentes são:

* tmin_*: temperatura mínima média mensal histórica
* tmax_*: temperatura máxima média mensal histórica
* temp_media_*: temperatura média mensal histórica, derivada de * tmin e tmax
* ppt_*: precipitação mensal histórica
* pet_*: evapotranspiração potencial mensal histórica
* aet_*: evapotranspiração real mensal histórica
* def_*: déficit hídrico mensal histórico

Cada sufixo mensal corresponde a um mês do ano:

*jan, fev, mar, abr, mai, jun, jul, ago, set, out, nov, dez*

Assim, por exemplo:

* temp_media_jan representa a média histórica de temperatura média para todos os janeiros do período processado
* ppt_mar representa a média histórica de precipitação para todos os meses de março do período processado
* def_set representa a média histórica de déficit hídrico para todos os meses de setembro do período processado

As unidades utilizadas são:
* temperaturas (*tmin, tmax, temp_media*): **graus Celsius (°C)**
* precipitação (*ppt*): **milímetros por mês (mm/mês)**
* evapotranspiração potencial (*pet*): **milímetros por mês (mm/mês)**
* evapotranspiração real (*aet*): **milímetros por mês (mm/mês)**
* déficit hídrico (*def*): **milímetros por mês (mm/mês)**

In [4]:
#Importando um arquivo .csv dos dados de temperatura dos municípios
df = pd.read_csv('https://raw.githubusercontent.com/andr3nf/clima_municipios_brasileiros/refs/heads/main/clima_historico_municipal.csv')

# Comandos para visualização geral dos dados

In [5]:
'''
Chamar apenas o dataframe para visualização, usa-se o nome do dataframe, neste caso o df
Quando o dataframe é muito grande ele apresenta as primeiras e últimas 5 linhas
Info: Gerson Battisti
'''
# visualiza todo DataFrame
df

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
0,1100015,Alta Floresta D'Oeste,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.18,25.23,25.57,...,0.00,2.45,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29
1,1100023,Ariquemes,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.29,25.39,25.59,...,0.00,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00
2,1100031,Cabixi,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.85,25.80,26.13,...,0.00,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04
3,1100049,Cacoal,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.69,24.84,25.18,...,0.00,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00
4,1100056,Cerejeiras,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.84,25.82,26.18,...,0.00,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,5222005,Vianópolis,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,22.55,22.67,22.73,...,2.36,9.14,31.73,50.22,79.46,103.54,92.59,35.55,3.85,0.01
5566,5222054,Vicentinópolis,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.23,24.62,24.66,...,2.39,11.55,36.91,58.97,84.52,110.33,91.72,33.09,5.48,0.00
5567,5222203,Vila Boa,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.73,24.74,24.75,...,7.63,14.68,44.94,63.04,91.81,113.21,104.04,52.02,7.87,6.10
5568,5222302,Vila Propício,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.02,24.16,24.18,...,4.17,10.77,37.17,55.68,85.60,115.28,95.54,38.63,2.24,2.53
5569,5300108,Brasília,DF,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,21.88,22.00,21.92,...,3.09,8.42,31.06,46.80,74.12,99.77,91.04,40.31,2.58,0.83

# Comandos para visualização parcial dos dados
Visualição rápida, mas não total, das informações

In [26]:
'''
Visualiza apenas as 5 primeiras linhas do dataframe.
Forma rápida de visualizar parcialmente os dados sem mostrar todo o dataframe.
Info: Brendha
'''

# visualiza as 5 primeiras linhas
df.head(5)

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
0,1100015,Alta Floresta D'Oeste,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.18,25.23,25.57,...,0.0,2.45,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29
1,1100023,Ariquemes,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.29,25.39,25.59,...,0.0,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00
2,1100031,Cabixi,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.85,25.80,26.13,...,0.0,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04
3,1100049,Cacoal,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.69,24.84,25.18,...,0.0,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00
4,1100056,Cerejeiras,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.84,25.82,26.18,...,0.0,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36

# Como saber a quantidade de linhas e colunas do dataframe

In [25]:
'''
O comando shape mostra a quantidade de linhas e colunas do dataframe.
A posição [0] representa a quantidade de linhas e a posição [1] representa a quantidade de colunas.
Info: Brendha
'''

# cria uma cópia do dataframe
df_copia = df.copy()

# mostra a quantidade de linhas e colunas
df_copia.shape

(5570, 91)

# Como renomear o nome das colunas

In [24]:
'''
O comando rename permite alterar o nome de uma ou mais colunas do dataframe.
Neste exemplo, a coluna nome_municipio será alterada para municipio.
Info: Brendha
'''

# cria uma cópia do dataframe
df_copia = df.copy()

# renomeia a coluna
df_copia.rename(columns={'nome_municipio': 'municipio'}, inplace=True)

# visualiza o dataframe
df_copia.head()

,codigo_ibge,municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
0,1100015,Alta Floresta D'Oeste,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.18,25.23,25.57,...,0.0,2.45,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29
1,1100023,Ariquemes,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.29,25.39,25.59,...,0.0,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00
2,1100031,Cabixi,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.85,25.80,26.13,...,0.0,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04
3,1100049,Cacoal,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.69,24.84,25.18,...,0.0,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00
4,1100056,Cerejeiras,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.84,25.82,26.18,...,0.0,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36

# Como adicionar linhas ao dataframe

In [23]:
'''
Para adicionar uma nova linha ao dataframe pode utilizar o comando loc.
A nova linha é inserida na última posição do dataframe.
Info: Brendha
'''

# cria uma cópia do dataframe
df_copia = df.copy()

# copia uma linha existente
nova_linha = df_copia.iloc[0].copy()

# altera algumas informações
nova_linha['codigo_ibge'] = 9999999
nova_linha['nome_municipio'] = 'Municipio Exemplo'

# adiciona a nova linha
df_copia.loc[len(df_copia)] = nova_linha

# visualiza as últimas linhas
df_copia.tail()

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
5566,5222054,Vicentinópolis,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.23,24.62,24.66,...,2.39,11.55,36.91,58.97,84.52,110.33,91.72,33.09,5.48,0.00
5567,5222203,Vila Boa,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.73,24.74,24.75,...,7.63,14.68,44.94,63.04,91.81,113.21,104.04,52.02,7.87,6.10
5568,5222302,Vila Propício,GO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.02,24.16,24.18,...,4.17,10.77,37.17,55.68,85.60,115.28,95.54,38.63,2.24,2.53
5569,5300108,Brasília,DF,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,21.88,22.00,21.92,...,3.09,8.42,31.06,46.80,74.12,99.77,91.04,40.31,2.58,0.83
5570,9999999,Municipio Exemplo,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.18,25.23,25.57,...,0.00,2.45,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29

# Como adicionar colunas ao dataframe

In [22]:
'''
Para adicionar uma nova coluna precisa informar o nome da nova coluna entre colchetes.
Neste exemplo será criada uma coluna com a temperatura média anual dos municípios.
Info: Brendha
'''

# cria uma cópia do dataframe
df_copia = df.copy()

# cria uma nova coluna
df_copia['temp_media_anual'] = df_copia[
    ['temp_media_jan', 'temp_media_fev', 'temp_media_mar',
     'temp_media_abr', 'temp_media_mai', 'temp_media_jun',
     'temp_media_jul', 'temp_media_ago', 'temp_media_set',
     'temp_media_out', 'temp_media_nov', 'temp_media_dez']
].mean(axis=1)

# visualiza o dataframe
df_copia.head()

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez,temp_media_anual
0,1100015,Alta Floresta D'Oeste,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.18,25.23,25.57,...,2.45,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29,25.174167
1,1100023,Ariquemes,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.29,25.39,25.59,...,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00,25.514167
2,1100031,Cabixi,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.85,25.80,26.13,...,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04,25.589167
3,1100049,Cacoal,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.69,24.84,25.18,...,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00,24.926667
4,1100056,Cerejeiras,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.84,25.82,26.18,...,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36,25.658333

# Como deletar linhas

In [21]:
'''
O comando drop permite excluir linhas do dataframe.
Neste exemplo será removida a linha de índice 0.
Info: Brendha
'''

# cria uma cópia do dataframe
df_copia = df.copy()

# exclui a linha de índice 0
df_copia.drop(index=0, inplace=True)

# visualiza o dataframe
df_copia.head()

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
1,1100023,Ariquemes,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.29,25.39,25.59,...,0.0,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00
2,1100031,Cabixi,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.85,25.80,26.13,...,0.0,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04
3,1100049,Cacoal,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.69,24.84,25.18,...,0.0,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00
4,1100056,Cerejeiras,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.84,25.82,26.18,...,0.0,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36
5,1100064,Colorado do Oeste,RO,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.07,25.04,25.36,...,0.0,1.02,15.11,31.31,49.38,64.13,48.22,6.51,2.67,0.00

# Como deletar colunas

In [20]:
'''
O comando drop pode ser utilizado para excluir colunas do dataframe.
Para isso é utilizado o parâmetro columns informando a coluna que será removida.
Info: Brendha
'''

# cria uma cópia do dataframe
df_copia = df.copy()

# exclui uma coluna
df_copia.drop(columns=['metodo_processamento'], inplace=True)

# visualiza o dataframe
df_copia.head()

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,temp_media_jan,temp_media_fev,temp_media_mar,temp_media_abr,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
0,1100015,Alta Floresta D'Oeste,RO,1975,2024,TerraClimate,25.18,25.23,25.57,25.26,...,0.0,2.45,14.87,31.74,50.42,64.80,46.20,11.53,2.90,0.29
1,1100023,Ariquemes,RO,1975,2024,TerraClimate,25.29,25.39,25.59,25.54,...,0.0,0.29,5.65,29.46,46.09,53.95,19.80,1.41,0.06,0.00
2,1100031,Cabixi,RO,1975,2024,TerraClimate,25.85,25.80,26.13,25.71,...,0.0,1.65,16.77,31.91,49.42,67.96,55.16,10.79,4.60,0.04
3,1100049,Cacoal,RO,1975,2024,TerraClimate,24.69,24.84,25.18,24.87,...,0.0,0.44,14.36,31.44,48.04,60.16,29.09,5.23,1.08,0.00
4,1100056,Cerejeiras,RO,1975,2024,TerraClimate,25.84,25.82,26.18,25.79,...,0.0,2.67,17.16,33.05,53.29,74.58,60.96,11.31,4.35,0.36

# Como mesclar dois dataframe

In [19]:
'''
O comando merge permite unir dois dataframes utilizando uma coluna em comum.
Neste exemplo os dataframes são unidos através da coluna codigo_ibge.
Info: Brendha
'''

# cria uma cópia do dataframe
df_copia = df.copy()

# cria dois dataframes menores
df_temperatura = df_copia[['codigo_ibge', 'nome_municipio', 'temp_media_jan']]
df_chuva = df_copia[['codigo_ibge', 'ppt_jan']]

# mescla os dois dataframes
df_mesclado = pd.merge(df_temperatura, df_chuva, on='codigo_ibge')

# visualiza o resultado
df_mesclado.head()

   codigo_ibge         nome_municipio  temp_media_jan  ppt_jan
0      1100015  Alta Floresta D'Oeste           25.18   259.78
1      1100023              Ariquemes           25.29   334.41
2      1100031                 Cabixi           25.85   314.01
3      1100049                 Cacoal           24.69   373.13
4      1100056             Cerejeiras           25.84   295.31

# Buscar uma linha ou uma célula (linha e coluna) específica

In [28]:
'''
O comando loc permite localizar linhas e colunas específicas do dataframe.
Neste exemplo será pesquisado o município de Ijuí e sua temperatura média de janeiro.
Info: Brendha
'''

# cria uma cópia do dataframe
df_copia = df.copy()

# localiza a linha do município de Ijuí
df_copia.loc[df_copia['nome_municipio'] == 'Ijuí']

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
4807,4310207,Ijuí,RS,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,24.63,24.25,22.77,...,21.89,9.66,3.05,0.32,1.36,4.95,2.97,3.39,21.45,34.25

In [29]:
'''
E para buscar apenas uma célula
'''

_IncompleteInputError: incomplete input (458764131.py, line 1)

# Buscar linhas de forma condicional

# Buscar um dataframe parcial (Linhas e Colunas específicas)

# Como agrupar valores de uma coluna. Semelhante a banco de dados: Groupby

# Criar um dataframe a partir de um dicionário

# Como deletar linhas com valores vazios

# Como preencher valores vazios

# Comandos para inserir colunas de peso e altura no sistema universal